dockers:
  - image_templates:
      - "keinos/helloworld:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "keinos/helloworld:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
  - image_templates:
      - "keinos/helloworld:{{ .Version }}-armv6"
    use: buildx
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
  - image_templates:
      - "keinos/helloworld:{{ .Version }}-armv7"
    use: buildx
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"

# Build multiarch manifest file of Docker image
docker_manifests:
  - name_template: keinos/helloworld:{{ .Version }}
    image_templates:
      - keinos/helloworld:{{ .Version }}-amd64
      - keinos/helloworld:{{ .Version }}-arm64
      - keinos/helloworld:{{ .Version }}-armv6
      - keinos/helloworld:{{ .Version }}-armv7
  - name_template: keinos/helloworld:latest
    image_templates:
      - keinos/helloworld:{{ .Version }}-amd64
      - keinos/helloworld:{{ .Version }}-arm64
      - keinos/helloworld:{{ .Version }}-armv6
      - keinos/helloworld:{{ .Version }}-armv7
