# Settings to build the binaries. These binaries will be used to build the Docker images.
builds:
  -
    # Target directory of main.go package
    main: ./cmd/helloworld
    # Output binary name
    binary: helloworld
    # Target OS
    goos:
      - linux
    # Target architectures
    goarch:
      - amd64
      - arm
      - arm64
    # Variant for ARM32
    goarm:
      - "5"
      - "6"
      - "7"
    # Ignore ARM32/ARM64 build for both macOS and Windows
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
    # Build the app as static binary and embed version and commit info
    ldflags:
      - -s -w -extldflags '-static' -X 'main.version={{.Version}}' -X 'main.commit={{ .ShortCommit }}'

dockers:
  - image_templates:
      - "keinos/helloworld:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "keinos/helloworld:{{ .Version }}-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"

  - image_templates:
      - "keinos/helloworld:{{ .Version }}-armv5"
    use: buildx
    goarch: arm
    goarm: 5
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v5"

  - image_templates:
      - "keinos/helloworld:{{ .Version }}-armv6"
    use: buildx
    goarch: arm
    goarm: 6
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"

  - image_templates:
      - "keinos/helloworld:{{ .Version }}-armv7"
    use: buildx
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"

# Build multiarch manifest file of Docker image
docker_manifests:
  - name_template: keinos/helloworld:{{ .Version }}
    image_templates:
      - keinos/helloworld:{{ .Version }}-amd64
      - keinos/helloworld:{{ .Version }}-arm64
      - keinos/helloworld:{{ .Version }}-armv5
      - keinos/helloworld:{{ .Version }}-armv6
      - keinos/helloworld:{{ .Version }}-armv7
  - name_template: keinos/helloworld:latest
    image_templates:
      - keinos/helloworld:{{ .Version }}-amd64
      - keinos/helloworld:{{ .Version }}-arm64
      - keinos/helloworld:{{ .Version }}-armv5
      - keinos/helloworld:{{ .Version }}-armv6
      - keinos/helloworld:{{ .Version }}-armv7
